# Generated by Django 4.1.7 on 2023-05-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipcr',
            old_name='Num_syllabus_prepared_Target',
            new_name='Target_syllabus_prepared',
        ),
    ]
