# Generated by Django 4.1.7 on 2023-05-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_rename_num_syllabus_prepared_target_ipcr_target_syllabus_prepared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipcr',
            old_name='Target_syllabus_prepared',
            new_name='Num_syllabus_prepared_Target',
        ),
    ]
