# Generated by Django 4.1.7 on 2023-05-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_rename_target_syllabus_prepared_ipcr_num_syllabus_prepared_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcr',
            name='Num_syllabus_prepared_Accomplished',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
