# Generated by Django 4.1.7 on 2023-05-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_ipcr_num_syllabus_prepared_accomplished'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IPCR',
            new_name='IPCR_Syllabus_model',
        ),
    ]
