# Generated by Django 4.1.7 on 2023-05-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_remove_ipcr_syllabus_model_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipcr_syllabus_model',
            name='user',
        ),
    ]
