# Generated by Django 4.1.7 on 2023-05-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_alter_ipcr_syllabus_model_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcr_syllabus_model',
            name='author',
            field=models.IntegerField(default=1),
        ),
    ]
